### ISSUE TITLE
[Bug][Clarification needed] Kube-fledged every `controllerImageCacheRefreshFrequency` downloads some images

### ISSUE THREAD

**Issue by bkupidura** [senthilrch/kube-fledged#121] opened 2021-10-20 07:26 UTC
I observed that `kube-fledged` every `controllerImageCacheRefreshFrequency` (15m by default) downloads some images - even when image is available on worker.

Kube-fledged version: v0.8.2
Kube-fledged installation method: helm.

```
I1020 06:59:12.135352       1 image_manager.go:365] Started image manager
[...]
I1020 06:59:12.249271       1 image_manager.go:446] Job imagecache-tm5tf created (pull:- eclipse-mosquitto:2.0.12 --> k3s-charlie, runtime: containerd://1.4.9-k3s1)
I1020 06:59:12.261454       1 image_manager.go:446] Job imagecache-6zvms created (pull:- eclipse-mosquitto:2.0.12 --> k3s-delta, runtime: containerd://1.4.9-k3s1)
I1020 06:59:12.350650       1 image_manager.go:446] Job imagecache-vf668 created (pull:- eclipse-mosquitto:2.0.12 --> k3s-bravo, runtime: containerd://1.4.9-k3s1)
I1020 06:59:14.097144       1 image_manager.go:181] Job imagecache-tm5tf succeeded (pull:- eclipse-mosquitto:2.0.12 --> k3s-charlie, runtime: containerd://1.4.9-k3s1)
I1020 06:59:15.470289       1 image_manager.go:181] Job imagecache-6zvms succeeded (pull:- eclipse-mosquitto:2.0.12 --> k3s-delta, runtime: containerd://1.4.9-k3s1)
I1020 06:59:15.860805       1 image_manager.go:181] Job imagecache-vf668 succeeded (pull:- eclipse-mosquitto:2.0.12 --> k3s-bravo, runtime: containerd://1.4.9-k3s1)
I1020 06:59:16.402314       1 controller.go:430] Starting to sync image cache imagecache(statusupdate)
I1020 06:59:16.432549       1 controller.go:635] Completed sync actions for image cache imagecache(statusupdate)
[...]
I1020 07:14:11.939659       1 controller.go:430] Starting to sync image cache imagecache(refresh)
I1020 07:14:12.137280       1 controller.go:635] Completed sync actions for image cache imagecache(refresh)
I1020 07:14:12.148497       1 image_manager.go:446] Job imagecache-vlvk4 created (pull:- eclipse-mosquitto:2.0.12 --> k3s-bravo, runtime: containerd://1.4.9-k3s1)
I1020 07:14:12.153446       1 image_manager.go:446] Job imagecache-k5zls created (pull:- eclipse-mosquitto:2.0.12 --> k3s-charlie, runtime: containerd://1.4.9-k3s1)
I1020 07:14:12.158658       1 image_manager.go:446] Job imagecache-hldn7 created (pull:- eclipse-mosquitto:2.0.12 --> k3s-delta, runtime: containerd://1.4.9-k3s1)
[...]
I1020 07:14:13.896099       1 image_manager.go:181] Job imagecache-k5zls succeeded (pull:- eclipse-mosquitto:2.0.12 --> k3s-charlie, runtime: containerd://1.4.9-k3s1)
I1020 07:14:14.469347       1 image_manager.go:181] Job imagecache-vlvk4 succeeded (pull:- eclipse-mosquitto:2.0.12 --> k3s-bravo, runtime: containerd://1.4.9-k3s1)
I1020 07:14:15.156943       1 image_manager.go:181] Job imagecache-hldn7 succeeded (pull:- eclipse-mosquitto:2.0.12 --> k3s-delta, runtime: containerd://1.4.9-k3s1)
```

Image is already on worker:
```
root@k3s-delta:~# crictl images ls |grep -E 'eclipse-mosquitto\W+2.0.12'
docker.io/library/eclipse-mosquitto                2.0.12                  a45972533f35b       5.61MB
```

Other images works as expected. 

First guess would be that K8s GC removes this image, but it is not the case as POD using this image is running on one of the nodes all the time.

**Comment by senthilrch** [comment] 2021-10-20 08:23
This is super weird..The resources in a node, including images present in the node are periodically sent to kube-apiserver by the kubelet on that node. It means kubelet doesn't recognizes the mosquitto image on the node..

**Comment by senthilrch** [comment] 2021-12-27 11:13
Kube-fledged relies on the list of images reported in Node.Staus.Images to determine whether an image is already present in the Node or not. In case an image actually present in the container runtime of the Node is not reported, kube-fledged assumes the image is not present and creates a job to pull the image. If the flag --image-pull-policy is set to "IfNotPresent", the job will exit without pulling the image. Only when the flag is set to "Always", the image is re-pulled.

By default, the kubelet flag --node-status-max-images has a value "50" i.e. kubelet will report only a max. of 50 images to the API server in it's node status update. This is a pretty large number and in majority of the environments this should result in all images being reported. K8s security best practices advices to keep only the useful images in the cluster nodes and periodically remove unused images. So the number of cases where the node needs to hold more than 50 useful images would be much lower.

Redesigning kube-fledged to cater to the small number of cases where the node would hold more than 50 useful images would be costly. In any case repulling the image that is already present in the node would never lead to undesirable behaviour. It would increase network traffic to the image registry. If more users report this as a problem in future, then we can revisit this issue. For now it is recommended to close it.

Many thanks to @bkupidura for the relentless investigations in finding the root cause of the behaviour. The kube-fledged team completely appreciate your efforts. Thank You!!

**Closed by senthilrch** 2021-12-27 11:13 UTC
